### ISSUE TITLE
Optional support for `tungstenite::Message` instead of `WsMessage`

### ISSUE THREAD

**Issue by bitfl0wer** [najamelan/ws_stream_wasm#13]
Hi! I am writing a library which relies on websockets, and is supposed to work on Desktop and `wasm`-environments alike. As many people do, I have chosen tungstenite Desktop Websockets, and I have found this crate to be my best bet when it comes to adopting my code for the `wasm32-unknown-unknown` compile target triple.

I was quite happy to see that this crate implements `futures_util` traits like `Sink<T>` and `Stream`, offering me the possibility to have my code compile for both my major targets using the same code, plus some generics.

Sadly, this isn't possible yet, and here's why:

`futures_util::Sink<Item>` means, that two implementations of `Sink` can only be used via generics in the same code base, if they implement that Trait for the same `Item`. However, `tungstenite` implements `Sink` over *their* Message type, while tjos crate uses its' own message type instead. On it's own, this is completely fine. However, adding an optional feature to `ws_stream_wasm` which allows for something like `tungstenite::Message` to be used instead, while not having to duplicate code within `ws_stream_wasm`, would make this possible. I believe that doing this is possible, and I am offering to implement this myself, if this is something that the maintainers of this crate would like, which is what I'd like to ask for with this issue.

I think that such an optional feature would make supporting `wasm32`-flavours way easier for all developers.

**Comment by najamelan** [comment]
Well, you will never run the same code on both targets. So you can just detect the platform/add a feature on your crate. 

Pseudocode:

```rust
#[cfg(target_arch = "wasm32")]
impl Sink<ws_stream_wasm::Message> for MyStruct {...}

#[cfg(not(target_arch = "wasm32"))]
impl Sink<tungstenite::Message> for Mystruct {...}
```

Let me know if I misunderstood what you are trying to do. You can even share the actual implementation by putting it directly in an `impl` block for you type.

**Comment by bitfl0wer** [comment]
Yes, you can do that, however, I don't want to implement `Sink` in my crate, as I feel like that'd be out of the scope of what the crate is trying to achieve.
I'd like to be able to create a trait bound on my Websocket wrapper type, which says, that anything which implements `Sink<tungstenite::Message>` is valid to be used as `T`. This would allow me to have implementations for both a non-wasm and a wasm-websocket using a lot of shared code, and only minor adjustments needed for either implementation. If ws_stream_wasm were to support implementing its `Stream` type for other `Message` types as well, this would be possible.

**Comment by najamelan** [comment]
Let's try to establish what you are trying to do. Do you expose an API from your library that exposes `Sink`? Or does your type just want to use the `Sink`?

> I don't want to implement Sink in my crate, as I feel like that'd be out of the scope of what the crate is trying to achieve.

Let's just be clear that it's hard to imagine it being more out of scope than adding a dependency on tungstenite to a wasm crate. If not because tungstenite has no use on wasm (apart for your very niche use case), then because tungstenite releases a breaking change about once a month and I don't want to add that maintenance burden.

But no worries, there is many ways to solve this. Already if you just want to be a user of the `Sink`, you can define your struct twice:

```rust
#[cfg(target_arch = "wasm32")]
struct MyStruct<T> where T: Sink<ws_stream_wasm::Message> {...}

#[cfg(not(target_arch = "wasm32"))]
struct MyStruct<T> where T: Sink<tungstenite::Message> {...}
```

Personally I abstract over websockets using ws_stream_wasm and ws_stream_tungstenite because they both implement `AsyncRead`/`AsyncWrite`. This means I can treat the connection as a TCP connection basically and have my actor library work over just those traits which means I support UDS, named pipes, memory mapped files, you name it. 

This might not be appropriate for your use case. Just know there is different solutions possible and I think this should be solvable in your crate rather than upstream. Im happy to keep searching with you to find the most appropriate solution, so if the above doesn't work, please explain a bit more what you are trying to do or show some code for the API you are trying to create.

**Comment by bitfl0wer** [comment]
> Let's just be clear that it's hard to imagine it being more out of scope than adding a dependency on tungstenite to a wasm crate.

That's fair.
What do you think of my current implementation over at https://github.com/bitfl0wer/ws_stream_wasm/tree/feature/generic-message?

An implementation like this would allow one to use `WsStream` with *any* self-defined message type, simply by implementing the `Message` trait from the `ws_stream_wasm` crate for your own Message type. This would make it possible to define Structs which are generic over a type `Sink<T>` where `T` could be equal, solving a lot of headache when trying to implement something for both wasm and non-wasm.

P.S: *please* provide a rustfmt.toml if you'd like external contributors to adhere to your style guidelines 😅

**Comment by bitfl0wer** [comment]
:) Do you know that feeling when you've spent hours trying to debug your code/figuring out how to solve a problem and you THINK you've found a solution, but actually, that solution is totally nonsenical? Yeah, that was me, with this issue.

Sorry for taking up your time, and thank you for the help. However, I do still stand behind my rustfmt comment 😌

**Comment by najamelan** [comment]
Yep, a message trait is also an option, just you have to put it in your crate, as that way you can implement it for any type you want. In ws_stream_wasm I would have to implement it for all the types you want to support, so not that handy. Glad you found a solution.
