### ISSUE TITLE
WsStream is not Send anymore in 0.7

### ISSUE THREAD

**Issue by sinhpham** [najamelan/ws_stream_wasm#5]
Due to the `closer` field being `Option< Pin<Box< dyn Future< Output=() > >> >,` and that's not `Send` https://github.com/najamelan/ws_stream_wasm/blob/c4e9d91f15d9c63b9c24db8a39c233aaee189f74/src/ws_stream.rs#L54

This makes using `ws_stream_wasm` in multi platform projects hard. A potential fix is to wrap `closer` in a `SendWrapper` just like other fields in `WsStream`.

**Comment by najamelan** [comment]
My apologies for this oversight. This was of course not intentional and has been fixed in version 0.7.2. I suppose that should be satisfactory, so I'll close the issue, but feel free to reopen if there is anything else.

Just to be clear, this crate is not meant to be compiled in when compiling for other targets. It's strictly wasm only and the types aren't really `Send`.

**Comment by sinhpham** [comment]
Thank you for addressing the issue so quick, I appreciate it.

Yes we're using `ws_stream_wasm` for `wasm` only, but our project targets multiple platforms. For those we're using `tokio` so a lot of shared code has `+ Send` requirement.

**Comment by sinhpham** [comment]
@najamelan we actually also need `+ Sync`, previously all fields were wrapped in `SendWrapper` which makes the whole `WsStream` `Sync`.

**Comment by najamelan** [comment]
Ah, I see. We can't reasonably have the future be `Sync`, so yes I wrapped it in `SendWrapper`. I released version 0.7.3.
